### ISSUE TITLE
New Tests causing errors being logged when running in PROD

### ISSUE THREAD

**Issue by softinio** [maciej-gol/tenant-schemas-celery#24]
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/usr/local/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 672, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 678, in _autodiscover_tasks_from_names
    packages() if callable(packages) else packages, related_name,
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    related_name) if mod)
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 246, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 263, in find_related_module
    return importlib.import_module('{0}.{1}'.format(package, related_name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas_celery/tasks.py", line 1, in <module>
    @app.task
```

**Comment by softinio** [comment]
Seems you are not importing `app` here: 

https://github.com/maciej-gol/tenant-schemas-celery/blob/master/tenant_schemas_celery/tasks.py

I know this is only used for tests but its causing above noise in our PROD logs so we had to revert so thought I bring to your attention. 

Thanks so much for all help.

**Comment by maciej-gol** [comment]
Thanks, Will look into that!

śr., 10 paź 2018, 23:41 użytkownik Salar Rahmanian <notifications@github.com>
napisał:

**Comment by maciej-gol** [comment]
fixed in `0.2.1`
